# Generated by Django 3.1.1 on 2020-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0002_auto_20201214_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('alarmPassword', models.CharField(max_length=240)),
                ('userLogin', models.CharField(max_length=240)),
                ('userPassword', models.CharField(max_length=240)),
            ],
        ),
    ]
