# Generated by Django 3.1.4 on 2020-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0005_logsms_responsestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoalarm',
            name='phoneNumber',
            field=models.CharField(max_length=240),
        ),
    ]
